name: Build
on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: C++ version check
        run: |
          git submodule update --init
          docker build -t cpp-version-check .
          docker run --rm -v "$(pwd):/app" cpp-version-check 
